import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

describe("viewer UI assets", () => {
  it("ships structured sidebar topic links with active styling", async () => {
    const indexHtml = await readFile(join(process.cwd(), "viewer", "index.html"), "utf8");
    const mark = await readFile(join(process.cwd(), "viewer", "almanac-mark.png"));
    const appJs = await readFile(join(process.cwd(), "viewer", "app.js"), "utf8");
    const routesJs = await readFile(join(process.cwd(), "viewer", "routes.js"), "utf8");
    const jobsJs = await readFile(join(process.cwd(), "viewer", "jobs-view.js"), "utf8");
    const jobsTranscriptJs = await readFile(join(process.cwd(), "viewer", "jobs-transcript.js"), "utf8");
    const searchSuggestionsJs = await readFile(join(process.cwd(), "viewer", "search-suggestions.js"), "utf8");
    const appCss = await readFile(join(process.cwd(), "viewer", "app.css"), "utf8");
    const jobsCss = await readFile(join(process.cwd(), "viewer", "jobs.css"), "utf8");

    expect(mark.byteLength).toBeGreaterThan(0);
    expect(indexHtml).toContain('src="/almanac-mark.png"');
    expect(indexHtml).toContain('href="/jobs.css"');
    expect(indexHtml).toContain("Your code wiki");
    expect(indexHtml).toContain('class="ca-brand ca-brand-route"');
    expect(indexHtml).toContain('data-route="/"');
    expect(indexHtml).not.toContain("Local wiki viewer");
    expect(indexHtml).toContain("Linked from");
    expect(indexHtml).not.toContain("Backlinks");
    expect(indexHtml).toContain('data-route="/"');
    expect(indexHtml).toContain('data-route="/getting-started"');
    expect(indexHtml).toContain('data-route="/jobs"');
    expect(indexHtml).not.toContain("recent-list");
    expect(appJs).not.toContain("recentList");
    expect(appJs).toContain("featuredPages?.projectOverview");
    expect(appJs).toContain("featuredPages?.gettingStarted");
    expect(appJs).toContain("featuredPages?.gettingStarted ?? state.overview.featuredPages?.projectOverview");
    expect(appJs).not.toContain("const projectOverview = await optionalPage");
    expect(appJs).toContain("state.wikis");
    expect(appJs).toContain("state.currentWiki");
    expect(appJs).toContain("renderWikiDirectory");
    expect(appJs).toContain('from "./routes.js"');
    expect(appJs).toContain("/api/wikis");
    expect(appJs).toContain('pathname.startsWith("/w/")');
    expect(appJs).toContain("state.overview.topics");
    expect(appJs).toContain("topicNavigation?.source === \"curated\"");
    expect(appJs).toContain("const SIDEBAR_TAG_LIMIT = 8");
    expect(appJs).toContain("data-topic-toggle");
    expect(appJs).toContain("Show all topics");
    expect(appJs).toContain("Show fewer topics");
    expect(appJs).toContain("renderTopicTree");
    expect(appJs).toContain("topic.parents");
    expect(appJs).toContain("ca-topic-depth-");
    expect(appJs).toContain("state.overview.featuredPages");
    expect(appJs).toContain('wikiPath === "/getting-started"');
    expect(appJs).toContain("renderGettingStarted");
    expect(appJs).toContain("renderPageActions");
    expect(appJs).toContain("goBack");
    expect(appJs).toContain("almanacHistoryIndex");
    expect(appJs).toContain("history.replaceState");
    expect(appJs).toContain("event.state");
    expect(appJs).toContain("Back");
    expect(appJs).not.toContain("ca-page-header");
    expect(appJs).toContain("renderHeading");
    expect(appJs).toContain("renderMarkdown(page.body, { decorateTitle: true, summary: page.summary })");
    expect(appJs).toContain("function renderMarkdown(source, options = {})");
    expect(appJs).toContain("renderArticleSummary");
    expect(appJs).toContain('const level = decorated ? "h1" : "h2";');
    expect(appJs).toContain("ca-page-ornament");
    expect(appJs).toContain('wikiPath === "/jobs"');
    expect(appJs).toContain('wikiPath.startsWith("/jobs/")');
    expect(appJs).toContain('import { createJobsView } from "./jobs-view.js"');
    expect(appJs).toContain('import { createSearchSuggestions } from "./search-suggestions.js"');
    expect(appJs).toContain("searchSuggestions.wire");
    expect(appJs).toContain("jobsView.renderList");
    expect(appJs).toContain("jobsView.renderDetail");
    expect(appJs).toContain("jobsView.clearPoll");
    expect(appJs).not.toContain("state.jobPollTimer");
    expect(jobsJs).toContain("export function createJobsView");
    expect(jobsJs).toContain('from "./jobs-transcript.js"');
    expect(jobsJs).toContain("transcriptEntry");
    expect(jobsJs).toContain("colophonEntries");
    expect(jobsJs).toContain("groupByDay");
    expect(jobsJs).toContain("logEntry");
    expect(jobsJs).toContain("statusMark");
    expect(jobsJs).toContain("cleanSummary");
    expect(jobsJs).toContain("displayTitle");
    expect(jobsJs).toContain("displaySubtitle");
    expect(jobsJs).toContain("ca-tool-card");
    expect(jobsJs).toContain("ca-tool-summary");
    expect(jobsTranscriptJs).toContain("export function buildTranscript");
    expect(jobsTranscriptJs).toContain("getToolCardModel");
    expect(jobsTranscriptJs).toContain("toolsById");
    expect(searchSuggestionsJs).toContain("export function createSearchSuggestions");
    expect(searchSuggestionsJs).toContain("deps.suggestPath");
    expect(searchSuggestionsJs).not.toContain("/api/suggest");
    expect(jobsJs).toContain("deps.jobsPath()");
    expect(jobsJs).toContain("deps.jobPath(runId)");
    expect(jobsJs).toContain("deps.jobRoute(run.id)");
    expect(jobsJs).toContain("deps.isCurrentJobRoute(runId)");
    expect(jobsJs).toContain("deps.pageActions()");
    expect(jobsJs).toContain("schedulePoll");
    expect(appJs).not.toContain("Start with the map");
    expect(appJs).toContain("setRailVisible(isWikiPageRoute(pathname))");
    expect(appJs).toContain("ca-topic-link");
    expect(appJs).toContain("ca-link-label");
    expect(appJs).toContain("ca-link-detail");
    expect(appJs).toContain('querySelectorAll(".ca-left [data-route]")');
    expect(routesJs).toContain("isCrossWikiTarget");
    expect(routesJs).toContain('return `/w/${encodeURIComponent(wiki)}/page/${encodeURIComponent(slug)}`');
    expect(appJs).not.toContain("<br><small>");

    expect(appCss).toContain(".ca-topic-link");
    expect(appCss).toContain(".ca-brand-mark-image");
    expect(appCss).toContain(".ca-brand-route");
    expect(appCss).toContain(".ca-page-actions");
    expect(appCss).toContain(".ca-back-button");
    expect(appCss).toContain(".ca-article-summary");
    expect(appCss).toContain(".ca-page-ornament");
    expect(appCss).toContain(".ca-link-button");
    expect(appCss).toContain("brightness(0.68)");
    expect(appCss).toContain(".ca-left .ca-link-button.is-active");
    expect(appCss).not.toContain(".ca-left .ca-link-button {\n  color: var(--ca-text);");
    expect(appCss).toContain(".ca-shell.is-rail-hidden");
    expect(appCss).not.toContain(".ca-log-entry");
    expect(jobsCss).toContain(".ca-log-entry");
    expect(jobsCss).toContain(".ca-logbook");
    expect(jobsCss).toContain(".ca-log-day");
    expect(jobsCss).toContain(".ca-colophon");
    expect(jobsCss).toContain(".ca-transcript-section");
    expect(jobsCss).toContain(".ca-transcript");
    expect(jobsCss).toContain(".ca-chat-bubble");
    expect(jobsCss).toContain(".ca-tool-step");
    expect(jobsCss).toContain(".ca-tool-card");
    expect(jobsCss).toContain(".ca-tool-summary");
    expect(jobsCss).toContain(".ca-tool-facts");
    expect(jobsCss).not.toContain(".ca-event-row");
    expect(jobsCss).not.toContain(".ca-job-impact");
    expect(jobsCss).not.toContain(".ca-run-ledger");
    expect(jobsCss).toContain(".ca-status-tone-active");
    expect(jobsCss).toContain(".ca-status-tone-done");
    expect(jobsCss).toContain(".ca-status-tone-alert");
    expect(appCss).toContain(".ca-suggest");
    expect(appCss).toContain(".ca-suggest-item");
    expect(appCss).toContain(".ca-wiki-directory");
    expect(appCss).toContain(".ca-wiki-stats");
    expect(appCss).toContain("overflow-wrap: anywhere");
  });
});
