import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

describe("viewer UI assets", () => {
  it("ships structured sidebar topic links with active styling", async () => {
    const indexHtml = await readFile(join(process.cwd(), "viewer", "index.html"), "utf8");
    const mark = await readFile(join(process.cwd(), "viewer", "almanac-mark.png"));
    const appJs = await readFile(join(process.cwd(), "viewer", "app.js"), "utf8");
    const jobsJs = await readFile(join(process.cwd(), "viewer", "jobs-view.js"), "utf8");
    const jobsTranscriptJs = await readFile(join(process.cwd(), "viewer", "jobs-transcript.js"), "utf8");
    const searchSuggestionsJs = await readFile(join(process.cwd(), "viewer", "search-suggestions.js"), "utf8");
    const appCss = await readFile(join(process.cwd(), "viewer", "app.css"), "utf8");
    const jobsCss = await readFile(join(process.cwd(), "viewer", "jobs.css"), "utf8");

    expect(mark.byteLength).toBeGreaterThan(0);
    expect(indexHtml).toContain('src="/almanac-mark.png"');
    expect(indexHtml).toContain('href="/jobs.css"');
    expect(indexHtml).toContain("Your code wiki");
    expect(indexHtml).not.toContain("Local wiki viewer");
    expect(indexHtml).toContain('data-route="/getting-started"');
    expect(indexHtml).toContain('data-route="/jobs"');
    expect(indexHtml).not.toContain("recent-list");
    expect(appJs).not.toContain("recentList");
    expect(appJs).toContain("featuredPages?.projectOverview");
    expect(appJs).toContain("featuredPages?.gettingStarted");
    expect(appJs).toContain("featuredPages?.gettingStarted ?? state.overview.featuredPages?.projectOverview");
    expect(appJs).not.toContain("const projectOverview = await optionalPage");
    expect(appJs).toContain("state.overview.topics");
    expect(appJs).toContain("topicNavigation?.source === \"curated\"");
    expect(appJs).toContain("const SIDEBAR_TAG_LIMIT = 8");
    expect(appJs).toContain("data-topic-toggle");
    expect(appJs).toContain("Show all topics");
    expect(appJs).toContain("Show fewer topics");
    expect(appJs).toContain("renderTopicTree");
    expect(appJs).toContain("topic.parents");
    expect(appJs).toContain("ca-topic-depth-");
    expect(appJs).toContain("state.overview.featuredPages");
    expect(appJs).toContain('pathname === "/getting-started"');
    expect(appJs).toContain("renderGettingStarted");
    expect(appJs).toContain('pathname === "/jobs"');
    expect(appJs).toContain('pathname.startsWith("/jobs/")');
    expect(appJs).toContain('import { createJobsView } from "./jobs-view.js"');
    expect(appJs).toContain('import { createSearchSuggestions } from "./search-suggestions.js"');
    expect(appJs).toContain("searchSuggestions.wire");
    expect(appJs).toContain("jobsView.renderList");
    expect(appJs).toContain("jobsView.renderDetail");
    expect(appJs).toContain("jobsView.clearPoll");
    expect(appJs).not.toContain("state.jobPollTimer");
    expect(jobsJs).toContain("export function createJobsView");
    expect(jobsJs).toContain('from "./jobs-transcript.js"');
    expect(jobsJs).toContain("transcriptEntry");
    expect(jobsJs).toContain("runOutcomeStrip");
    expect(jobsJs).toContain("jobImpact");
    expect(jobsJs).toContain("cleanSummary");
    expect(jobsJs).toContain("displayTitle");
    expect(jobsJs).toContain("displaySubtitle");
    expect(jobsJs).toContain("ca-tool-card");
    expect(jobsJs).toContain("ca-tool-summary");
    expect(jobsTranscriptJs).toContain("export function buildTranscript");
    expect(jobsTranscriptJs).toContain("getToolCardModel");
    expect(jobsTranscriptJs).toContain("toolsById");
    expect(searchSuggestionsJs).toContain("export function createSearchSuggestions");
    expect(searchSuggestionsJs).toContain("/api/suggest");
    expect(jobsJs).toContain('deps.api("/api/jobs")');
    expect(jobsJs).toContain('deps.api(`/api/jobs/${encodeURIComponent(runId)}`)');
    expect(jobsJs).toContain("schedulePoll");
    expect(appJs).not.toContain("Start with the map");
    expect(appJs).toContain('setRailVisible(pathname.startsWith("/page/"))');
    expect(appJs).toContain("ca-topic-link");
    expect(appJs).toContain("ca-link-label");
    expect(appJs).toContain("ca-link-detail");
    expect(appJs).toContain('querySelectorAll(".ca-left [data-route]")');
    expect(appJs).not.toContain("<br><small>");

    expect(appCss).toContain(".ca-topic-link");
    expect(appCss).toContain(".ca-brand-mark-image");
    expect(appCss).toContain("brightness(0.68)");
    expect(appCss).toContain(".ca-left .ca-link-button.is-active");
    expect(appCss).toContain(".ca-shell.is-rail-hidden");
    expect(appCss).not.toContain(".ca-job-row");
    expect(jobsCss).toContain(".ca-job-row");
    expect(jobsCss).toContain(".ca-job-impact");
    expect(jobsCss).toContain(".ca-job-stream");
    expect(jobsCss).toContain(".ca-run-ledger");
    expect(jobsCss).toContain(".ca-transcript");
    expect(jobsCss).toContain(".ca-chat-bubble");
    expect(jobsCss).toContain(".ca-tool-step");
    expect(jobsCss).toContain(".ca-tool-card");
    expect(jobsCss).toContain(".ca-tool-summary");
    expect(jobsCss).toContain(".ca-tool-facts");
    expect(jobsCss).not.toContain(".ca-event-row");
    expect(jobsCss).toContain(".ca-status-running");
    expect(appCss).toContain(".ca-suggest");
    expect(appCss).toContain(".ca-suggest-item");
    expect(appCss).toContain("overflow-wrap: anywhere");
  });
});
